-- Gifi for OHADA French chart of accounts UTF-8
-- Classes et groupes de comptes pour le plan comptable OHADA
--
-- Gilles Adjallah <gmadjallah@protonmail.com>, 2020-07-25
--
--
SET client_encoding = 'UTF-8';
--
update gifi set description = 'CHARGES IMMOBILISÉES' where accno = 'AA'; 
update gifi set description = 'IMMOBILISATIONS INCORPORELLES' where accno = 'AD'; 
update gifi set description = 'Frais de recherche et de développement' where accno = 'AE'; 
update gifi set description = 'Brevets, licences, logiciels' where accno = 'AF'; 
update gifi set description = 'Fonds commercial' where accno = 'AG'; 
update gifi set description = 'Autres immobilisations incorporelles' where accno = 'AH'; 
update gifi set description = 'IMMOBILISATIONS CORPORELLES' where accno = 'AI'; 
update gifi set description = 'Terrains' where accno = 'AJ'; 
update gifi set description = 'Bâtiments' where accno = 'AK'; 
update gifi set description = 'Installations et agencements' where accno = 'AL'; 
update gifi set description = 'Matériel' where accno = 'AM'; 
update gifi set description = 'Matériel de transport' where accno = 'AN'; 
update gifi set description = 'AVANCES ET ACOMPTES VERSÉS SUR IMMOBILISATIONS' where accno = 'AP'; 
update gifi set description = 'IMMOBILISATIONS FINANCIÈRES' where accno = 'AQ'; 
update gifi set description = 'Titres de participation' where accno = 'AR'; 
update gifi set description = 'Autres immobilisations financières' where accno = 'AS'; 
update gifi set description = 'ACTIF CIRCULANT H.A.O.' where accno = 'BA'; 
update gifi set description = 'STOCKS' where accno = 'BB'; 
update gifi set description = 'Marchandises' where accno = 'BC'; 
update gifi set description = 'Matières premières et autres approvisionnements' where accno = 'BD'; 
update gifi set description = 'En-cours' where accno = 'BE'; 
update gifi set description = 'Produits fabriqués' where accno = 'BF'; 
update gifi set description = 'CRÉANCES ET EMPLOIS ASSIMILÉS' where accno = 'BG'; 
update gifi set description = 'Fournisseurs avances versées' where accno = 'BH'; 
update gifi set description = 'Clients' where accno = 'BI'; 
update gifi set description = 'Autres créances' where accno = 'BJ'; 
update gifi set description = 'Titres de placement' where accno = 'BQ'; 
update gifi set description = 'Valeurs à encaisser' where accno = 'BR'; 
update gifi set description = 'Banques, chèques postaux, caisse' where accno = 'BS'; 
update gifi set description = 'Écarts de conversion-Actif' where accno = 'BU'; 
update gifi set description = 'CAPITAL' where accno = 'CA'; 
update gifi set description = 'Actionnaires, capital souscrit non appelé' where accno = 'CB'; 
update gifi set description = 'PRIMES ET RÉSERVES' where accno = 'CC'; 
update gifi set description = 'Primes d’émission, d’apport, de fusion' where accno = 'CD'; 
update gifi set description = 'Écarts de réévaluation' where accno = 'CE'; 
update gifi set description = 'Réserves indisponibles' where accno = 'CF'; 
update gifi set description = 'Réserves libres' where accno = 'CG'; 
update gifi set description = 'Report à nouveau' where accno = 'CH'; 
update gifi set description = 'RÉSULTAT NET DE L’EXERCICE' where accno = 'CI'; 
update gifi set description = 'AUTRES CAPITAUX PROPRES' where accno = 'CK'; 
update gifi set description = 'Subventions d’investissement' where accno = 'CL'; 
update gifi set description = 'Provisions réglementées et fonds assimilés' where accno = 'CM'; 
update gifi set description = 'DETTES FINANCIÈRES ET RESSOURCES ASSIMILÉES' where accno = 'CP'; 
update gifi set description = 'Emprunts' where accno = 'DA'; 
update gifi set description = 'Dettes de crédit-bail et contrats assimilés' where accno = 'DB'; 
update gifi set description = 'Dettes financières diverses' where accno = 'DC'; 
update gifi set description = 'Provisions financières pour risques et charges' where accno = 'DD'; 
update gifi set description = 'Dettes circulantes H.A.O. et ressources assimilées ' where accno = 'DH'; 
update gifi set description = 'Clients, avances reçues' where accno = 'DI'; 
update gifi set description = 'Fournisseurs d''exploitation' where accno = 'DJ'; 
update gifi set description = 'Dettes fiscales' where accno = 'DK'; 
update gifi set description = 'Dettes sociales' where accno = 'DL'; 
update gifi set description = 'Autres dettes' where accno = 'DM'; 
update gifi set description = 'Risques provisionnés' where accno = 'DN'; 
update gifi set description = 'Banques, crédits d’escompte' where accno = 'DQ'; 
update gifi set description = 'Banques, crédits de trésorerie' where accno = 'DR'; 
update gifi set description = 'Banques, découverts' where accno = 'DS'; 
update gifi set description = 'Écarts de conversion - Passif' where accno = 'DV'; 
update gifi set description = 'Achat de marchandises ' where accno = 'RA'; 
update gifi set description = 'Variation de stocks' where accno = 'RB'; 
update gifi set description = 'Achat de matières premières et fournitures liées' where accno = 'RC'; 
update gifi set description = 'Variation de stocks' where accno = 'RD'; 
update gifi set description = 'Autres achats' where accno = 'RE'; 
update gifi set description = 'Variation de stocks' where accno = 'RH'; 
update gifi set description = 'Transports' where accno = 'RI'; 
update gifi set description = 'Services extérieurs' where accno = 'RJ'; 
update gifi set description = 'Impôts et taxes' where accno = 'RK'; 
update gifi set description = 'Autres charges' where accno = 'RL'; 
update gifi set description = 'Charges de personnel' where accno = 'RP'; 
update gifi set description = 'Dotations aux amortissements et aux provisions' where accno = 'RS'; 
update gifi set description = 'Frais financiers' where accno = 'SA'; 
update gifi set description = 'Pertes de change' where accno = 'SC'; 
update gifi set description = 'Dotations aux amortissements et aux provisions' where accno = 'SD'; 
update gifi set description = 'Valeurs comptables des cessions d''immobilisations' where accno = 'SK'; 
update gifi set description = 'Charges H.A.O.' where accno = 'SL'; 
update gifi set description = 'Dotations H.A.O.' where accno = 'SM'; 
update gifi set description = 'Participation des travailleurs' where accno = 'SQ'; 
update gifi set description = 'Impôts sur le résultat' where accno = 'SR'; 
update gifi set description = 'Ventes de marchandises' where accno = 'TA'; 
update gifi set description = 'Ventes de produits fabriqués' where accno = 'TC'; 
update gifi set description = 'Travaux, services vendus' where accno = 'TD'; 
update gifi set description = 'Production stockée' where accno = 'TE'; 
update gifi set description = 'Production immobilisée' where accno = 'TF'; 
update gifi set description = 'Produits accessoires' where accno = 'TH'; 
update gifi set description = 'Subventions d’exploitation' where accno = 'TK'; 
update gifi set description = 'Autres produits' where accno = 'TL'; 
update gifi set description = 'Reprises de provisions' where accno = 'TS'; 
update gifi set description = 'Transferts de charges' where accno = 'TT'; 
update gifi set description = 'Revenus financiers ' where accno = 'UA'; 
update gifi set description = 'Gains de change' where accno = 'UC'; 
update gifi set description = 'Reprises de provisions ' where accno = 'UD'; 
update gifi set description = 'Transferts de charges' where accno = 'UE'; 
update gifi set description = 'Produits des cessions d’immobilisations' where accno = 'UK'; 
update gifi set description = 'Produits H.A.O.' where accno = 'UL'; 
update gifi set description = 'Reprises H.A.O. ' where accno = 'UM'; 
update gifi set description = 'Transferts de charges' where accno = 'UN'; 
--
update sic set description = 'Agriculture vivrière' where code = '001'; 
update sic set description = 'Culture céréalière' where code = '001001'; 
update sic set description = 'Culture de tubercules et plantains' where code = '001002'; 
update sic set description = 'Culture de légumes' where code = '001003'; 
update sic set description = 'Culture de condiments' where code = '001004'; 
update sic set description = 'Culture de fruits' where code = '001005'; 
update sic set description = 'Culture d’autres produits de l’agriculture vivrière' where code = '001006'; 
update sic set description = 'Agriculture industrielle et d’exportation' where code = '002'; 
update sic set description = 'Culture de canne à sucre' where code = '002001'; 
update sic set description = 'Culture d’arachide d’huilerie' where code = '002002'; 
update sic set description = 'Culture d’arachide de bouche' where code = '002003'; 
update sic set description = 'Culture de tabac' where code = '002004'; 
update sic set description = 'Culture de coton' where code = '002005'; 
update sic set description = 'Culture de blé' where code = '002006'; 
update sic set description = 'Culture de cacao' where code = '002007'; 
update sic set description = 'Culture de café' where code = '002008'; 
update sic set description = 'Culture de bananes d’exportation' where code = '002009'; 
update sic set description = 'Culture d’ananas d’exportation' where code = '002010'; 
update sic set description = 'Autres cultures industrielles' where code = '002011'; 
update sic set description = 'Elevage et chasse' where code = '003'; 
update sic set description = 'Elevage bovin' where code = '003001'; 
update sic set description = 'Elevage ovin, caprin, équin' where code = '003002'; 
update sic set description = 'Elevage de volailles' where code = '003003'; 
update sic set description = 'Autres élevages' where code = '003004'; 
update sic set description = 'Chasse' where code = '003005'; 
update sic set description = 'Sylviculture, exploitation forestière' where code = '004'; 
update sic set description = 'Sylviculture' where code = '004001'; 
update sic set description = 'Exploitation forestière' where code = '004002'; 
update sic set description = 'Pêche et aquaculture' where code = '005'; 
update sic set description = 'Pêche de poissons' where code = '005001'; 
update sic set description = 'Autres pêches et aquaculture' where code = '005002'; 
update sic set description = 'Industries extractives' where code = '006'; 
update sic set description = 'Extraction d’hydrocarbures' where code = '006001'; 
update sic set description = 'Extraction d’autres produits' where code = '006002'; 
update sic set description = 'Production de viande et de poissons' where code = '007'; 
update sic set description = 'Production de viande et de produits à base de viande' where code = '007001'; 
update sic set description = 'Production de poissons et de produits à base de poissons' where code = '007002'; 
update sic set description = 'Travail des grains et fabrication de produits amylacés' where code = '008'; 
update sic set description = 'Travail des grains et fabrication de produits amylacés' where code = '008000'; 
update sic set description = 'Transformation du café et du cacao' where code = '009'; 
update sic set description = 'Transformation du café' where code = '009001'; 
update sic set description = 'Transformation du cacao' where code = '009002'; 
update sic set description = 'Industrie des oléagineux' where code = '010'; 
update sic set description = 'Huiles brutes et tourteaux' where code = '010001'; 
update sic set description = 'Autres corps gras' where code = '010002'; 
update sic set description = 'Boulangerie, pâtisserie et pâtes alimentaires' where code = '011'; 
update sic set description = 'Fabrication de pains, de biscuits et de pâtisserie' where code = '011001'; 
update sic set description = 'Fabrication de pâtes alimentaires' where code = '011002'; 
update sic set description = 'Industries laitières' where code = '012'; 
update sic set description = 'Industries laitières' where code = '012000'; 
update sic set description = 'Transformation des fruits et légumes et fabrication d’autres produits alimentaires' where code = '013'; 
update sic set description = 'Fabrication de sucre' where code = '013001'; 
update sic set description = 'Fabrication de produits à base de fruits et légumes' where code = '013002'; 
update sic set description = 'Fabrication d’autres produits alimentaires' where code = '013003'; 
update sic set description = 'Industrie des boissons' where code = '014'; 
update sic set description = 'Brasseries et malteries' where code = '014001'; 
update sic set description = 'Fabrication d’autres boissons alcoolisées' where code = '014002'; 
update sic set description = 'Fabrication de boissons non alcoolisées et d’eaux minérales' where code = '014003'; 
update sic set description = 'Industries du tabac' where code = '015'; 
update sic set description = 'Industries du tabac' where code = '015000'; 
update sic set description = 'Industries textiles et habillement' where code = '016'; 
update sic set description = 'Industries textiles' where code = '016001'; 
update sic set description = 'Industries de l’habillement' where code = '016002'; 
update sic set description = 'Industries du cuir et de la chaussure' where code = '017'; 
update sic set description = 'Fabrication du cuir et d’articles en cuir' where code = '017001'; 
update sic set description = 'Fabrication de chaussures' where code = '017002'; 
update sic set description = 'Industries du bois' where code = '018'; 
update sic set description = 'Sciage, rabotage et imprégnation du bois' where code = '018001'; 
update sic set description = 'Fabrication de panneaux en bois' where code = '018002'; 
update sic set description = 'Fabrication d’articles en bois assemblés' where code = '018003'; 
update sic set description = 'Industries du papier et cartons, de l’édition et de l’imprimerie' where code = '019'; 
update sic set description = 'Industries du papier et carton' where code = '019001'; 
update sic set description = 'Edition, imprimerie, reproduction' where code = '019002'; 
update sic set description = 'Raffinage du pétrole' where code = '020'; 
update sic set description = 'Raffinage de pétrole' where code = '02000'; 
update sic set description = 'Industrie chimique' where code = '021'; 
update sic set description = 'Industries chimiques de base' where code = '021001'; 
update sic set description = 'Fabrication de savons, de détergents et de produits d’entretien' where code = '021002'; 
update sic set description = 'Fabrication de produits agro-chimiques' where code = '021003'; 
update sic set description = 'Industries pharmaceutiques' where code = '021004'; 
update sic set description = 'Fabrication d’autres produits chimiques' where code = '021005'; 
update sic set description = 'Industries du caoutchouc et des plastiques' where code = '022'; 
update sic set description = 'Fabrication du caoutchouc naturel' where code = '022001'; 
update sic set description = 'Industries du caoutchouc' where code = '022002'; 
update sic set description = 'Fabrication de matières plastiques' where code = '022003'; 
update sic set description = 'Fabrication d’autres produits minéraux non métalliques et de matériaux de construction' where code = '023'; 
update sic set description = 'Industries du verre' where code = '023001'; 
update sic set description = 'Fabrication de produits minéraux pour la construction' where code = '023002'; 
update sic set description = 'Fabrication d’autres produits minéraux non métalliques' where code = '023003'; 
update sic set description = 'Métallurgie et travail des métaux' where code = '024'; 
update sic set description = 'Métallurgie' where code = '024001'; 
update sic set description = 'Travail des métaux' where code = '024002'; 
update sic set description = 'Fabrication de machines, d’équipements et d’appareils électriques' where code = '025'; 
update sic set description = 'Fabrication de machines et d’équipements' where code = '025001'; 
update sic set description = 'Fabrication de machines de bureau' where code = '025002'; 
update sic set description = 'Fabrication d’appareils électriques' where code = '025003'; 
update sic set description = 'Fabrication d’équipements et appareils audiovisuels et de communication ; fabrication d’instruments médicaux, d’optique et d’horlogerie' where code = '026'; 
update sic set description = 'Fabrication d’équipements et appareils audiovisuels et de communication' where code = '026001'; 
update sic set description = 'Fabrication d’instruments médicaux, d’optique et d’horlogerie' where code = '026002'; 
update sic set description = 'Fabrication de matériel de transport' where code = '027'; 
update sic set description = 'Fabrication de véhicules routiers' where code = '027001'; 
update sic set description = 'Fabrication d’autres matériels de transport' where code = '027002'; 
update sic set description = 'Industries diverses' where code = '028'; 
update sic set description = 'Fabrication de meubles' where code = '028001'; 
update sic set description = 'Industries diverses' where code = '028002'; 
update sic set description = 'Production et distribution d’eau, d’électricité et de gaz' where code = '029'; 
update sic set description = 'Production, transport et distribution d’électricité' where code = '029001'; 
update sic set description = 'Captage, épuration et distribution d’eau' where code = '029002'; 
update sic set description = 'Production et distribution de gaz' where code = '029003'; 
update sic set description = 'Construction' where code = '030'; 
update sic set description = 'Préparation de sites et construction d’ouvrages de bâtiments ou de génie civil' where code = '030001'; 
update sic set description = 'Travaux d’installation et de finition' where code = '030002'; 
update sic set description = 'Commerce' where code = '031'; 
update sic set description = 'Commerce de véhicules, d’accessoires et de carburant' where code = '031001'; 
update sic set description = 'Commerce de produits agricoles bruts et d’animaux vivants' where code = '031002'; 
update sic set description = 'Autres commerces' where code = '031003'; 
update sic set description = 'Réparations' where code = '032'; 
update sic set description = 'Entretien et réparation de véhicules automobiles' where code = '032001'; 
update sic set description = 'Réparations de biens personnels et domestiques' where code = '032002'; 
update sic set description = 'Hôtels, restaurants' where code = '033'; 
update sic set description = 'Hôtels' where code = '033001'; 
update sic set description = 'Bars et restaurants' where code = '033002'; 
update sic set description = 'Transport et communication' where code = '034'; 
update sic set description = 'Transports ferroviaires' where code = '034001'; 
update sic set description = 'Transports routiers ; transports par conduite' where code = '034002'; 
update sic set description = 'Transport par eau' where code = '034003'; 
update sic set description = 'Transports aériens' where code = '034004'; 
update sic set description = 'Services annexes et auxiliaires de transport' where code = '034005'; 
update sic set description = 'Postes, Télécommunications' where code = '035'; 
update sic set description = 'Postes' where code = '035001'; 
update sic set description = 'Télécommunications' where code = '035002'; 
update sic set description = 'Activités financières' where code = '036'; 
update sic set description = 'Services d’intermédiation financière' where code = '036001'; 
update sic set description = 'Assurance (sauf Sécurité sociale)' where code = '036002'; 
update sic set description = 'Auxiliaires financiers et d’assurances' where code = '036003'; 
update sic set description = 'Activités immobilières' where code = '037'; 
update sic set description = 'Locations de biens immobiliers' where code = '037001'; 
update sic set description = 'Autres services immobiliers' where code = '037002'; 
update sic set description = 'Services aux entreprises' where code = '038'; 
update sic set description = 'Locations sans opérateurs' where code = '038001'; 
update sic set description = 'Activités informatiques' where code = '038002'; 
update sic set description = 'Services rendus principalement aux entreprises' where code = '038003'; 
update sic set description = 'Administration publique' where code = '039'; 
update sic set description = 'Administration générale, économique et sociale' where code = '039001'; 
update sic set description = 'Services de prérogative publique' where code = '039002'; 
update sic set description = 'Sécurité sociale obligatoire' where code = '039003'; 
update sic set description = 'Education' where code = '040'; 
update sic set description = 'Education' where code = '040000'; 
update sic set description = 'Santé et action sociale' where code = '041'; 
update sic set description = 'Activités pour la santé des hommes' where code = '041001'; 
update sic set description = 'Activités vétérinaires' where code = '041002'; 
update sic set description = 'Action sociale' where code = '041003'; 
update sic set description = 'Services collectifs, sociaux et personnels' where code = '042'; 
update sic set description = 'Assainissement, voirie et gestion des déchets' where code = '042001'; 
update sic set description = 'Activités associatives' where code = '042002'; 
update sic set description = 'Activités récréatives, culturelles et sportives' where code = '042003'; 
update sic set description = 'Services personnels' where code = '042004'; 
update sic set description = 'Services domestiques' where code = '042005'; 
update sic set description = 'Service d’intermédiation financière indirectement mesuré' where code = '043'; 
update sic set description = 'Service d’intermédiation financière indirectement mesuré' where code = '043000'; 
update sic set description = 'Correction territoriale' where code = '044'; 
update sic set description = 'Correction territoriale' where code = '044000'; 
