-- Gifi for OHADA French chart of accounts UTF-8
-- Classes et groupes de comptes pour le plan comptable OHADA
--
-- Gilles Adjallah <gmadjallah@protonmail.com>, 2020-07-25
--
INSERT INTO gifi (accno, description) VALUES ('AA', 'CHARGES IMMOBILISÉES'); 
INSERT INTO gifi (accno, description) VALUES ('AD', 'IMMOBILISATIONS INCORPORELLES'); 
INSERT INTO gifi (accno, description) VALUES ('AE', 'Frais de recherche et de développement'); 
INSERT INTO gifi (accno, description) VALUES ('AF', 'Brevets, licences, logiciels'); 
INSERT INTO gifi (accno, description) VALUES ('AG', 'Fonds commercial'); 
INSERT INTO gifi (accno, description) VALUES ('AH', 'Autres immobilisations incorporelles'); 
INSERT INTO gifi (accno, description) VALUES ('AI', 'IMMOBILISATIONS CORPORELLES'); 
INSERT INTO gifi (accno, description) VALUES ('AJ', 'Terrains'); 
INSERT INTO gifi (accno, description) VALUES ('AK', 'Bâtiments'); 
INSERT INTO gifi (accno, description) VALUES ('AL', 'Installations et agencements'); 
INSERT INTO gifi (accno, description) VALUES ('AM', 'Matériel'); 
INSERT INTO gifi (accno, description) VALUES ('AN', 'Matériel de transport'); 
INSERT INTO gifi (accno, description) VALUES ('AP', 'AVANCES ET ACOMPTES VERSÉS SUR IMMOBILISATIONS'); 
INSERT INTO gifi (accno, description) VALUES ('AQ', 'IMMOBILISATIONS FINANCIÈRES'); 
INSERT INTO gifi (accno, description) VALUES ('AR', 'Titres de participation'); 
INSERT INTO gifi (accno, description) VALUES ('AS', 'Autres immobilisations financières'); 
INSERT INTO gifi (accno, description) VALUES ('BA', 'ACTIF CIRCULANT H.A.O.'); 
INSERT INTO gifi (accno, description) VALUES ('BB', 'STOCKS'); 
INSERT INTO gifi (accno, description) VALUES ('BC', 'Marchandises'); 
INSERT INTO gifi (accno, description) VALUES ('BD', 'Matières premières et autres approvisionnements'); 
INSERT INTO gifi (accno, description) VALUES ('BE', 'En-cours'); 
INSERT INTO gifi (accno, description) VALUES ('BF', 'Produits fabriqués'); 
INSERT INTO gifi (accno, description) VALUES ('BG', 'CRÉANCES ET EMPLOIS ASSIMILÉS'); 
INSERT INTO gifi (accno, description) VALUES ('BH', 'Fournisseurs avances versées'); 
INSERT INTO gifi (accno, description) VALUES ('BI', 'Clients'); 
INSERT INTO gifi (accno, description) VALUES ('BJ', 'Autres créances'); 
INSERT INTO gifi (accno, description) VALUES ('BQ', 'Titres de placement'); 
INSERT INTO gifi (accno, description) VALUES ('BR', 'Valeurs à encaisser'); 
INSERT INTO gifi (accno, description) VALUES ('BS', 'Banques, chèques postaux, caisse'); 
INSERT INTO gifi (accno, description) VALUES ('BU', 'Écarts de conversion-Actif'); 
INSERT INTO gifi (accno, description) VALUES ('CA', 'CAPITAL'); 
INSERT INTO gifi (accno, description) VALUES ('CB', 'Actionnaires, capital souscrit non appelé'); 
INSERT INTO gifi (accno, description) VALUES ('CC', 'PRIMES ET RÉSERVES'); 
INSERT INTO gifi (accno, description) VALUES ('CD', 'Primes d’émission, d’apport, de fusion'); 
INSERT INTO gifi (accno, description) VALUES ('CE', 'Écarts de réévaluation'); 
INSERT INTO gifi (accno, description) VALUES ('CF', 'Réserves indisponibles'); 
INSERT INTO gifi (accno, description) VALUES ('CG', 'Réserves libres'); 
INSERT INTO gifi (accno, description) VALUES ('CH', 'Report à nouveau'); 
INSERT INTO gifi (accno, description) VALUES ('CI', 'RÉSULTAT NET DE L’EXERCICE'); 
INSERT INTO gifi (accno, description) VALUES ('CK', 'AUTRES CAPITAUX PROPRES'); 
INSERT INTO gifi (accno, description) VALUES ('CL', 'Subventions d’investissement'); 
INSERT INTO gifi (accno, description) VALUES ('CM', 'Provisions réglementées et fonds assimilés'); 
INSERT INTO gifi (accno, description) VALUES ('CP', 'DETTES FINANCIÈRES ET RESSOURCES ASSIMILÉES'); 
INSERT INTO gifi (accno, description) VALUES ('DA', 'Emprunts'); 
INSERT INTO gifi (accno, description) VALUES ('DB', 'Dettes de crédit-bail et contrats assimilés'); 
INSERT INTO gifi (accno, description) VALUES ('DC', 'Dettes financières diverses'); 
INSERT INTO gifi (accno, description) VALUES ('DD', 'Provisions financières pour risques et charges'); 
INSERT INTO gifi (accno, description) VALUES ('DH', 'Dettes circulantes H.A.O. et ressources assimilées '); 
INSERT INTO gifi (accno, description) VALUES ('DI', 'Clients, avances reçues'); 
INSERT INTO gifi (accno, description) VALUES ('DJ', 'Fournisseurs d''exploitation'); 
INSERT INTO gifi (accno, description) VALUES ('DK', 'Dettes fiscales'); 
INSERT INTO gifi (accno, description) VALUES ('DL', 'Dettes sociales'); 
INSERT INTO gifi (accno, description) VALUES ('DM', 'Autres dettes'); 
INSERT INTO gifi (accno, description) VALUES ('DN', 'Risques provisionnés'); 
INSERT INTO gifi (accno, description) VALUES ('DQ', 'Banques, crédits d’escompte'); 
INSERT INTO gifi (accno, description) VALUES ('DR', 'Banques, crédits de trésorerie'); 
INSERT INTO gifi (accno, description) VALUES ('DS', 'Banques, découverts'); 
INSERT INTO gifi (accno, description) VALUES ('DV', 'Écarts de conversion - Passif'); 
INSERT INTO gifi (accno, description) VALUES ('RA', 'Achat de marchandises '); 
INSERT INTO gifi (accno, description) VALUES ('RB', 'Variation de stocks'); 
INSERT INTO gifi (accno, description) VALUES ('RC', 'Achat de matières premières et fournitures liées'); 
INSERT INTO gifi (accno, description) VALUES ('RD', 'Variation de stocks'); 
INSERT INTO gifi (accno, description) VALUES ('RE', 'Autres achats'); 
INSERT INTO gifi (accno, description) VALUES ('RH', 'Variation de stocks'); 
INSERT INTO gifi (accno, description) VALUES ('RI', 'Transports'); 
INSERT INTO gifi (accno, description) VALUES ('RJ', 'Services extérieurs'); 
INSERT INTO gifi (accno, description) VALUES ('RK', 'Impôts et taxes'); 
INSERT INTO gifi (accno, description) VALUES ('RL', 'Autres charges'); 
INSERT INTO gifi (accno, description) VALUES ('RP', 'Charges de personnel'); 
INSERT INTO gifi (accno, description) VALUES ('RS', 'Dotations aux amortissements et aux provisions'); 
INSERT INTO gifi (accno, description) VALUES ('SA', 'Frais financiers'); 
INSERT INTO gifi (accno, description) VALUES ('SC', 'Pertes de change'); 
INSERT INTO gifi (accno, description) VALUES ('SD', 'Dotations aux amortissements et aux provisions'); 
INSERT INTO gifi (accno, description) VALUES ('SK', 'Valeurs comptables des cessions d''immobilisations'); 
INSERT INTO gifi (accno, description) VALUES ('SL', 'Charges H.A.O.'); 
INSERT INTO gifi (accno, description) VALUES ('SM', 'Dotations H.A.O.'); 
INSERT INTO gifi (accno, description) VALUES ('SQ', 'Participation des travailleurs'); 
INSERT INTO gifi (accno, description) VALUES ('SR', 'Impôts sur le résultat'); 
INSERT INTO gifi (accno, description) VALUES ('TA', 'Ventes de marchandises'); 
INSERT INTO gifi (accno, description) VALUES ('TC', 'Ventes de produits fabriqués'); 
INSERT INTO gifi (accno, description) VALUES ('TD', 'Travaux, services vendus'); 
INSERT INTO gifi (accno, description) VALUES ('TE', 'Production stockée'); 
INSERT INTO gifi (accno, description) VALUES ('TF', 'Production immobilisée'); 
INSERT INTO gifi (accno, description) VALUES ('TH', 'Produits accessoires'); 
INSERT INTO gifi (accno, description) VALUES ('TK', 'Subventions d’exploitation'); 
INSERT INTO gifi (accno, description) VALUES ('TL', 'Autres produits'); 
INSERT INTO gifi (accno, description) VALUES ('TS', 'Reprises de provisions'); 
INSERT INTO gifi (accno, description) VALUES ('TT', 'Transferts de charges'); 
INSERT INTO gifi (accno, description) VALUES ('UA', 'Revenus financiers '); 
INSERT INTO gifi (accno, description) VALUES ('UC', 'Gains de change'); 
INSERT INTO gifi (accno, description) VALUES ('UD', 'Reprises de provisions '); 
INSERT INTO gifi (accno, description) VALUES ('UE', 'Transferts de charges'); 
INSERT INTO gifi (accno, description) VALUES ('UK', 'Produits des cessions d’immobilisations'); 
INSERT INTO gifi (accno, description) VALUES ('UL', 'Produits H.A.O.'); 
INSERT INTO gifi (accno, description) VALUES ('UM', 'Reprises H.A.O. '); 
INSERT INTO gifi (accno, description) VALUES ('UN', 'Transferts de charges'); 

